from typing import Protocol


class IOProtocol(Protocol):
    """Storage adapter you can swap for S3/GCS later."""

    def read(self, path: str) -> bytes: ...
    def write(self, path: str, data: bytes) -> None: ...
    def list(self, prefix: str) -> list[str]: ...
    def makedirs(self, path: str) -> None: ...
    def exists(self, path: str) -> bool: ...
